### ISSUE TITLE
Display and save of cropped image on APEX 19.1

### ISSUE THREAD

**Issue by BernhardFW** [maxime-tremblay/apex-plugin-imagecropper#2]
Hi Max,
I appreciate ur efforts on the plugin ! Thats awsome !
It might be an APEX 19.1 issue... 
updated 22.09.2019 12:00h:
but the preview is not displayed
Do you hv time to test this on APEX 19.1 ?
And 2 questions on this:
![Apex_cropper_image_shud_be_vertical](https://user-images.githubusercontent.com/28298512/65385533-232f9380-dd30-11e9-9310-4d91ea65ef37.png)
A) how can the image display reflect vertical images? 
here (in the screenshot)  one 3rd of the image on top and bottom is cut off.
B) how can the crop-box rectangle be bigger - say: 95 % of the picture (as the start)?
reason why: my users most likely will accept the default size of the crop-box rectangle.
thanks
I did donate some kudos for your allowing for a dinner or beer.
I am prepared to donate some extra kudos that you can invite a friend as well...
-  if you can get it running. JJJJ
Bernhard

**Comment by BernhardFW** [comment]
Hi Maximilian,
meanwhile I managed to save the  record fm the collection into my table, but not cropped/resized.
It's just the same as the source.
The preview is not showing up.
Any idea. Help wud be strongly appreciated - $$$$ €€€€€.
thks.
Bernhard

**Comment by maxime-tremblay** [comment]
Hello Bernhard

Yes it works in APEX 19.1. I have it setup on [askMax](https://askmax.solution).

a) is probably due to some CSS
b) there is a setting for that somewhere if I'm not mistaken. Let me look it up and come back to you

The best and easiest would be that you create a simple application on apex.oracle.com and share the credentials. I will then be able to have a look at it and make it work.

Regards
Maxime

**Comment by BernhardFW** [comment]
Hi Maxime,
today we had the first tests utilizing your Plugin - it worked well.

Performance:
wud it be possible to just compress the taken image (we use an iPad and the image.jpg is about 2 MB) straight away ?

Presently the steps are (with an iPad):
1. APEX --> file browse
2. open iPad camera
3. take picture
4. APEX display: render/show picture and preview image (this takes about 10 -15 secs - and this is to optimize)
5. save picture

I mean: can we skip step 4 ? and how ?
- can't we store/insert the compressed image directly into the target table ? instead of first into the collection... and then select from the collection and insert in my private table(AK_BILDER) ?

Thanks
